// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ybvbauidxwrudeqmlept.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidmJhdWlkeHdydWRlcW1sZXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxODc5OTIsImV4cCI6MjA0Nzc2Mzk5Mn0.Z5E1jEi0NVz7SUuIOELIpWRs1b4DwjIEdxYgjQ05Ogg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);